name: Docker couchdb_ext PR CI build

on:
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker docker_couchdb_ext72 image
        run: docker build -f Dockerfile72 -t docker_couchdb_ext72 .
      - name: Build Docker docker_couchdb_ext73 image
        run: docker build -f Dockerfile73 -t docker_couchdb_ext73 .
      - name: Build Docker docker_couchdb_ext74 image
        run: docker build -f Dockerfile74 -t docker_couchdb_ext74 .
